name: mongo_cron
description: Use MongoDB collection as a job queue for cron jobs.
version: 1.0.0
repository: https://github.com/dinko7/mongo_cron
homepage: https://github.com/dinko7/mongo_cron

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mongo_dart: ^0.10.3
  easy_cron: ^0.9.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
