name: mongo_cron
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mongo_dart: ^0.10.3
  easy_cron: ^0.9.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
